### ISSUE TITLE
Using fetch-retry with fetchMock does not work

### ISSUE THREAD

**Issue by matt2xu** [jonbern/fetch-retry#5]
Hi @jonbern ,

I've started using `fetch-retry` in my React application, it works fine until I run the tests. We're using [`fetch-mock`](http://www.wheresrhys.co.uk/fetch-mock/) to mock fetch calls to the server, and it appears that `fetch` is no longer mocked. According to the [troubleshooting](http://www.wheresrhys.co.uk/fetch-mock/troubleshooting) section of the `fetch-mock` documentation, this can happen if `fetch` is imported/required in a local variable, rather than using the global variable.

After checking the source code of `fetch-retry`, I see that this is indeed the case:

```js
var fetch = require('isomorphic-fetch');
```

Since `isomorphic-fetch` adds `fetch` as a global, it appears that it is not necessary to import `fetch` in a local variable in `fetch-retry`. That would also make `fetch-retry` work seamlessly with fetch-mock (and I suspect other mocking libraries too). Similarly, we could use the `Promise` global directly according to the [es6-promise documentation](https://github.com/stefanpenner/es6-promise).

Would you be open to a pull request for that?

Cheers,
Matthieu

**Comment by jonbern** [comment]
Hi @matt2xu,

Thanks for letting me know about the issue, and for the suggested fix. 

I've published a new version of the library with your suggestion (version 1.2.1).

I hope this solves your issues. If not, please let me know what I can do to help.

Cheers,
Jon K.

**Comment by matt2xu** [comment]
That was fast :)

I've just updated to 1.2.1 and tested, it solves the issue.

Thank you!
