### ISSUE TITLE
[Feature-Request] Compatability with browsers' fetch API

### ISSUE THREAD

**Issue by ilyaigpetrov** [jonbern/fetch-retry#56]
Hi.

I would be awesome if could use your library in modern browsers (Chromium and Firefox).

Thank you for your work,
Ilya.

**Comment by dwiyatci** [comment]
Hi @ilyaigpetrov, 👋😃 I came across your issue when I was looking for the build file to be included to my playground in https://jsfiddle.net - seems like I've got the same issue. 

So I created a PR to bundle the source code for browser usage, using `rollup`. Meanwhile, you could use the build file here:
https://cdn.jsdelivr.net/gh/dwiyatci/fetch-retry@master/dist/fetch-retry.umd.js

The `retryFetch` will be available as a global variable/object (attached to the browser's global / `window`).
