### ISSUE TITLE
When function is provided to `retryOn`, retries value is not honored

### ISSUE THREAD

**Issue by bradyclifford** [jonbern/fetch-retry#61]
In the example below, when passing in retries of 1, it defaults to that of 3.  For some reason the retries is overwritten by the default value when a function is passed into retryOn.

```
fetch(url, {
    retries: 1,
    retryOn: function(attempt, error, response) {
      if (error !== null || response.status >= 400) {
        console.log(`retrying, attempt number ${attempt + 1}`);
        return true;
      }
    })
    .then(function(response) {
      return response.json();
    }).then(function(json) {
      // do something with the result
      console.log(json);
    });
```

When just pass an array to `retryOn`, it honors my retries value.
```
fetch(url, {
      retries: 1,
      retryOn: [503]
    })
    .then(function(response) {
      return response.json();
    }).then(function(json) {
      // do something with the result
      console.log(json);
    });
```

**Comment by ptolemybarnes** [comment]
I guess if you pass the `retryOn` function then you're responsible for deciding whether to retry or not yourself. The value of `retries` is ignored. So if you wanted to only retry once then you'd return `attempt === 0` or something from `retryOn`.

**Comment by jonbern** [comment]
What @ptolemybarnes wrote is correct, with the current implementation of `retryOn` as a function, the `retries` argument is ignored and you are responsible for instructing the library whether or not to retry the the request.

In my view, using `retryOn` as a function is an edge case and specifying it as an array should cover most use-cases, unless you're working with a poorly designed API 🥲

**Comment by bradyclifford** [comment]
Thanks @jonbern .  I just want to also return on an error.  Shown in the example:
https://github.com/jonbern/fetch-retry#example-retry-custom-behavior
