### ISSUE TITLE
5.0.0 doesn't work in Node environment (e.g. with `node-fetch`)

### ISSUE THREAD

**Issue by paulrosania** [jonbern/fetch-retry#62]
👋🏼 Hi!

We noticed strange errors when attempting to upgrade 5.0.0, throughout our unit tests. Anywhere we invoked a `fetch-retry`-wrapped `fetch`, we got this error:
```
ReferenceError: Request is not defined
```

It traces to this PR: https://github.com/jonbern/fetch-retry/pull/59. `Request` isn't part of Node's global environment, so [this check](https://github.com/jonbern/fetch-retry/pull/59/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R65) causes a `ReferenceError`. This applies regardless of `fetch` implementation, so I think it will unfortunately break all projects using Node.

I think a `typeof Request !== 'undefined'` prior to the `instanceof` check might be enough to fix things for Node. I would normally put up a PR but I'm swamped at the moment -- I can follow up on this when I have more time if that would be helpful.

**Comment by knotthere** [comment]
Hi @paulrosania - I will create a PR to support the `node` environment.

**Comment by paulrosania** [comment]
Thank you!

**Comment by jonbern** [comment]
Many thanks for reporting the issue, and for suggesting a fix. I have merged @knotthere's PR and published a new release.

**Comment by paulrosania** [comment]
Thanks both! 5.0.1 is working for us. :)
