### ISSUE TITLE
307 Redirect

### ISSUE THREAD

**Issue by bradyclifford** [jonbern/fetch-retry#66]
In some cases an API endpoint can return a 307 redirect with a location header to another endpoint.  Currently, `fetch-retry` will reattempt using the original endpoint instead of the new location.  Is there a way to update the original request with the new endpoint during a subsequent retry?

This of course is enabled by default with fetch.
https://developer.mozilla.org/en-US/docs/Web/API/fetch

![image](https://user-images.githubusercontent.com/8923247/138758850-087cd3d9-5ff1-4a92-a247-56cc0b391f10.png)

**Comment by jonbern** [comment]
I would assume that unless you have configured `fetch-retry` to retry requests with a 307 status code, that the default behavior of the fetch implementation is what would be used.

Alternatively, if you are actively retrying 307 status codes, I think this is perhaps an edge-case where the current implementation falls short. By defining a custom `retryOn` function you get get a hold of the returned response object and get the `Location` header, but I don't see how you can replace the URL of the already wrapped fetch invocation.
