### ISSUE TITLE
Behaviour after retries are expired

### ISSUE THREAD

**Issue by liddellj** [jonbern/fetch-retry#7]
Hi there - firstly, thanks very much for putting this awesome library out there - much appreciated!

I have a wee suggestion on the behaviour when the maximum number of retries is reached without a successful response. Currently, the promise is rejected:
https://github.com/jonbern/fetch-retry/blob/88007a6e50e2ba0a44697ea09202af9ba8ffbffa/index.js#L39

However, the underlying fetch API does not behave this way, instead - it returns a response object with the appropriate status code. For fetch-retry to be a 'drop-in' replacement for the fetch API, I think it should behave in the same way, and resolve the promise with the most recent response, rather than rejecting it:
```js
         resolve(response);
```

I'm interested to hear your thoughts and I'm happy to submit a PR if you like?

**Comment by jonbern** [comment]
I'm glad you like the library, and thanks for the suggestion! 

This is something I overlooked in how the fetch API works, and I think it makes a lot of sense to change the current behaviour. I will create a new major version with the updated behaviour.

**Comment by jonbern** [comment]
Your suggestion has been implemented in #9.

Again, thanks for the suggestion!
