### ISSUE TITLE
Browser usage

### ISSUE THREAD

**Issue by ckir** [jonbern/fetch-retry#75]
Please show us a working example for how you use fetch-retry in a browser.

**Comment by medmin** [comment]
And also, can we use it with await and async ? Thanks

**Comment by derSascha** [comment]
The repository has a README with working examples.

If like to replace fetch at global level: 
```
const orignalFetch = window.fetch;
window.fetch = require('fetch-retry')(originalFetch, { retries: 3 });
```

This should work as the usual fetch, together with await and async as well.

**Comment by ckir** [comment]
I've asked for a working example because my problem was not how to use it but how to load it. And this is the line of code I was looking for

`import('./fetch-retry.umd.js').then(m => module = m).catch((err) => {console.log(err.message)});`

P.S. You also need the right server to load it. The python -m http.server I was using will not do the job. Switched to Web Server for Chrome and it works like a charm.

**Comment by jonbern** [comment]
Good that you found a solution 👍 

Most modern web apps use a JS bundler like webpack or esbuild, which makes the import easier and more streamlined. The downside is that it adds a build step, and you will need to configure the bundler.

Perhaps another alternative could be to add it directly in a `<script>` in your HTML file?
