### ISSUE TITLE
I want to update fetch-retry after v3 but it didn't work

### ISSUE THREAD

**Issue by guoguokakukaku** [jonbern/fetch-retry#78]
Thanks for the great fetch-retry! I use it from v2.0.0
I do it using fetch-retry like this.

```
fetchRetry('https://xxxx', {
      mode: "cors",
      method: "POST",
      headers: {
         "Content-Type": "application/json;charset=utf-8",
         Accept: "application/json",
      },
      retries: 3,
      retryDelay: 800,
      body: 'xxxxxxxx',
    }),
```

It works fine up to ver:2.2.3, but ver:3.x.x or later can't communicate normally.
Communication is no response and there is no error, 
and it is not possible to update after ver3. 
What should I do, has anything changed since ver3?

Thank you very much!

**Comment by jonbern** [comment]
Hello,

Up until version 3.0.0 `fetch-retry` came bundled with `isomorphic-fetch` and used that to wrap "fetch". In later versions, this is no longer the case, and you have to install a fetch library yourself, and then wrap that with `fetch-retry` (see the code example below). 

The advantage of this approach is that you get to decide which package to use, and most likely you already have a packed installed, so installing fetch-retry will not have a big impact on your overall bundle size. In addition, this also means that `fetch-retry` doesn't need any production dependencies itself which is a great bonus. The downside is that it's a little bit more hassle to  setup `fetch-retry` initially in your project.

```
var originalFetch = require('isomorphic-fetch');
var fetch = require('fetch-retry')(originalFetch);

fetch(url, {
    retries: 3,
    retryDelay: 1000
  })
  .then(function(response) {
    return response.json();
  })
  .then(function(json) {
    // do something with the result
    console.log(json);
  });
```

**Comment by guoguokakukaku** [comment]
Dear Jonbern. Thank you very much!
I was able to solve it with your suggestion
