### ISSUE TITLE
docs: works with native fetch?

### ISSUE THREAD

**Issue by MentalGear** [jonbern/fetch-retry#81]
Maybe indicate whether the package also works with the native fetch ?

**Comment by ClarenceL** [comment]
On Node 18 it does work for me with native fetch

**Comment by MentalGear** [comment]
What's your setup? doesnt work for me.

**Comment by jonbern** [comment]
I can confirm that the package should work with Node.js version 18.

I have updated the documentation with an example on how to wrap the node's native version of `fetch`

```
// fetch-retry can also wrap Node.js's native fetch API implementation:
const fetch = require('fetch-retry')(global.fetch);
```
