### ISSUE TITLE
incopatibility with `@types/node@18.18.9` or `@types/node@20.8.7`

### ISSUE THREAD

**Issue by Ludorio** [jonbern/fetch-retry#89]
I upgrade to `@types/node@18.18.9` or `@types/node@20.8.7` and dependence `undici-types` switch from "5.25.1" to "5.26.4": this leads to the error in the screenshot 
![screen1](https://github.com/jonbern/fetch-retry/assets/77192069/0306d9b2-a061-4038-8e35-3f1c39ea738e)

(Both of @types/node get the undici-types "~5.26.4")
![Schermata del 2023-11-09 11-09-18](https://github.com/jonbern/fetch-retry/assets/77192069/6584d770-a321-4c7a-a52f-7d040f113b6d)

Hope this can help!
Thanks in advance!

**Comment by jonbern** [comment]
Thanks for reporting this issue. There was a PR reporting a similar issue which I have closed: https://github.com/jonbern/fetch-retry/pull/88

In my closing comment I also suggested a work-around for how to use `fetch-retry` with `undici`.

**Comment by jonbern** [comment]
Please disregard my previous comment. 

After thinking about the issue more and better understanding @alecmev's code changes, I merged his changes and released a new version `6.0.0` which fixes this issue by allowing more permissive wrapping of fetch libraries.
