### ISSUE TITLE
Suggestion: Add an onRetry callback for reporting/logging

### ISSUE THREAD

**Issue by ViktorCollin** [jonbern/fetch-retry#90]
First of all I want to thank you for providing this wrapper, great work!

I have a small suggestion that I think could be useful for multiple users of this package.

I wanted a way to send metrics / logs when ever a retry is scheduled to happen, but could not find a good place to inject that. Right now I have modified the `retryDelay` function to emit the logs as a workaround, but feels a bit hacky.

I suggest adding a optional setting called `onRetry` which could be a function with the following signature 
```
function(attempt, maxRetries, delay, error, response)
```
The function should be called (if given) right before the `setTimeout` call in `retry` function https://github.com/jonbern/fetch-retry/blob/master/index.js#L126

I can help with the implementation if you want to, just let me know what you think about the idea before i start.

**Comment by ViktorQvarfordt** [comment]
It is possible to do the logging in the `retryDelay` function. I have something like this:

```
import fetchRetry from 'fetch-retry'

const fetchWithRetry = fetchRetry(fetch, {
  retryOn: [429, 500, 501, 502, 503, 504],
  retries: 15,
  retryDelay: (attempt) => {
    console.log(`Fetch retry attempt ${attempt + 1}`)
    
    // Exponential backoff with +/- 50% jitter
    return Math.pow(2, attempt) * 1000 * (Math.random() + 0.5)
  },
})
```

**Comment by jonbern** [comment]
It's a good suggestion, but I want to avoid making the API surface larger than what it currently is. The original idea behind `fetch-retry` was that it should be a simple wrapper with a stable and predictable API.

Instead of using the `retryDelay` function, which I agree is quite hacky, I would consider using a custom `retryOn` function as shown below:

```TypeScript
import fetchRetry from 'fetch-retry';

const fetchWrapped = fetchRetry(fetch, {
  retryOn: (attempt, error, response): boolean => {
    if (attempt < 3) {
      logger.warn(`Retry attempt: ${attempt}`)
      return true;
    } else {
      logger.warn(`Maximum retries reached. Giving up`)
      return false;
    }
  },
});
```

This enables you to also log the attempt number, when the library gives up retrying, and the reason why the request failed (found in the error or in the response). 

The downside is that it forces you to implement your own retry-logic, but in most cases where you didn't need to define a custom `onRetry` already, this should be quite trivial.

**Comment by esetnik** [comment]
@jonbern I don't think this example is correct. If the request is successful then we get a log warning `Maximum retries reached. Giving up`. It should be updated to be something like this:

```ts
    retryOn: (attempt, error, response): boolean => {
      // attempts exceeded case
      if (attempt > 3) {
        console.warn(`Maximum retries reached. Giving up`, { signedUrl });
        return false;
      }

      if (!response?.ok || error !== null) {
        console.warn(`Retry attempt: ${attempt}`, { signedUrl });
        return true;
      }

      // success case
      return false;
    },
```

**Comment by esetnik** [comment]
> It's a good suggestion, but I want to avoid making the API surface larger than what it currently is. The original idea behind `fetch-retry` was that it should be a simple wrapper with a stable and predictable API.
> 
> Instead of using the `retryDelay` function, which I agree is quite hacky, I would consider using a custom `retryOn` function as shown below:
> 
> ```ts
> import fetchRetry from 'fetch-retry';
> 
> const fetchWrapped = fetchRetry(fetch, {
>   retryOn: (attempt, error, response): boolean => {
>     if (!response?.ok || error) {
>       logger.warn(`Retry attempt: ${attempt}`)
>       return true;
>     } else {
>       logger.warn(`Maximum retries reached. Giving up`)
>       return false;
>     }
>   },
> });
> ```
> 
> This enables you to also log the attempt number, when the library gives up retrying, and the reason why the request failed (found in the error or in the response).
> 
> The downside is that it forces you to implement your own retry-logic, but in most cases where you didn't need to define a custom `onRetry` already, this should be quite trivial.
> 
> // Edited to fix example that wasn't working as expected.

@jonbern I don't think this example is correct. If the request is successful then we get a log warning `Maximum retries reached. Giving up`. It should be updated to be something like this:

```ts
    retryOn: (attempt, error, response): boolean => {
      // attempts exceeded case
      if (attempt > 3) {
        logger.warn(`Maximum retries reached. Giving up`);
        return false;
      }

      if (!response?.ok || error !== null) {
        logger.warn(`Retry attempt: ${attempt}`);
        return true;
      }

      // success case
      return false;
    },
```
