### ISSUE TITLE
upgrade guide to v6

### ISSUE THREAD

**Issue by mbrevda** [jonbern/fetch-retry#91]
Not following the changes in the new v6. Any chance an upgrade guide can be provided to help smooth the transition?

**Comment by jonbern** [comment]
For most users there should be no breaking changes in v6, but the signature for the wrapping function has changed (albeit being more permissive now), and we no longer include the triple-slash directive for DOM types (which no longer are in use by the library). 

This means there shouldn't be any breaking changes, but we can't guarantee it, so I decided it was safest to create a new major version. It is the goal of `fetch-retry` to not introduce breaking changes and that it should provide a stable API.

**Comment by mbrevda** [comment]
I didn't understand the types changes in the types, but a colleague got it sorted. Thanks!
